// Copyright (c) 2026 HSTLES / ORBTR Pty Ltd. All Rights Reserved.
// Queries: licensing@hstles.com
//
// ContentTopic wire formats — single-blob and chunked manifests.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: content.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ContentAdvert publishes "I hold this hash" to the swarm. Lives on the
// `content.advert.<fabric>` topic. Adverts are time-bounded; holders
// republish at half-TTL.
type ContentAdvert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          []byte                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`                                // SHA256 of content (or manifest for chunked)
	Holder        []byte                 `protobuf:"bytes,2,opt,name=holder,proto3" json:"holder,omitempty"`                            // NodeID
	ExpiresAt     int64                  `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`    // unix nanoseconds
	Size          uint32                 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`                               // bytes (advisory for capacity-aware fetcher)
	IsManifest    bool                   `protobuf:"varint,5,opt,name=is_manifest,json=isManifest,proto3" json:"is_manifest,omitempty"` // when true, hash addresses a Manifest (chunked)
	Sig           []byte                 `protobuf:"bytes,6,opt,name=sig,proto3" json:"sig,omitempty"`                                  // Ed25519 by holder over (hash || holder || expires_at || size || is_manifest)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentAdvert) Reset() {
	*x = ContentAdvert{}
	mi := &file_content_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentAdvert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentAdvert) ProtoMessage() {}

func (x *ContentAdvert) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentAdvert.ProtoReflect.Descriptor instead.
func (*ContentAdvert) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{0}
}

func (x *ContentAdvert) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *ContentAdvert) GetHolder() []byte {
	if x != nil {
		return x.Holder
	}
	return nil
}

func (x *ContentAdvert) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *ContentAdvert) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ContentAdvert) GetIsManifest() bool {
	if x != nil {
		return x.IsManifest
	}
	return false
}

func (x *ContentAdvert) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

// ContentLocateQuery is broadcast when a fetcher has zero local holders
// for a hash. Lives on `content.locate.<fabric>` topic. Subscribers reply
// (via a separate point-to-point RPC) if they hold the hash.
type ContentLocateQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          []byte                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Requester     []byte                 `protobuf:"bytes,2,opt,name=requester,proto3" json:"requester,omitempty"` // NodeID
	Sig           []byte                 `protobuf:"bytes,3,opt,name=sig,proto3" json:"sig,omitempty"`             // Ed25519 by requester
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentLocateQuery) Reset() {
	*x = ContentLocateQuery{}
	mi := &file_content_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentLocateQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentLocateQuery) ProtoMessage() {}

func (x *ContentLocateQuery) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentLocateQuery.ProtoReflect.Descriptor instead.
func (*ContentLocateQuery) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{1}
}

func (x *ContentLocateQuery) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *ContentLocateQuery) GetRequester() []byte {
	if x != nil {
		return x.Requester
	}
	return nil
}

func (x *ContentLocateQuery) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

// ContentLocateResponse is a point-to-point reply to a Locate query.
// Carries a fresh ContentAdvert so the requester can index it.
type ContentLocateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Advert        *ContentAdvert         `protobuf:"bytes,1,opt,name=advert,proto3" json:"advert,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentLocateResponse) Reset() {
	*x = ContentLocateResponse{}
	mi := &file_content_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentLocateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentLocateResponse) ProtoMessage() {}

func (x *ContentLocateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentLocateResponse.ProtoReflect.Descriptor instead.
func (*ContentLocateResponse) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{2}
}

func (x *ContentLocateResponse) GetAdvert() *ContentAdvert {
	if x != nil {
		return x.Advert
	}
	return nil
}

// Manifest describes a chunked content blob. Lives in the body of a
// swarm.Record on a content topic, indexed by BlobHash.
type Manifest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlobHash      []byte                 `protobuf:"bytes,1,opt,name=blob_hash,json=blobHash,proto3" json:"blob_hash,omitempty"`           // SHA256 of full reassembled content
	TotalSize     uint64                 `protobuf:"varint,2,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`       // bytes
	ChunkSize     uint32                 `protobuf:"varint,3,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`       // typically 1 MB (1<<20); last chunk may be smaller
	Chunks        [][]byte               `protobuf:"bytes,4,rep,name=chunks,proto3" json:"chunks,omitempty"`                               // SHA256 of each chunk, in order
	Filename      string                 `protobuf:"bytes,5,opt,name=filename,proto3" json:"filename,omitempty"`                           // optional human-readable name (debug only — untrusted)
	Mime          string                 `protobuf:"bytes,6,opt,name=mime,proto3" json:"mime,omitempty"`                                   // optional content-type hint
	PublishedAt   int64                  `protobuf:"varint,7,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"` // unix nanoseconds
	Publisher     []byte                 `protobuf:"bytes,8,opt,name=publisher,proto3" json:"publisher,omitempty"`                         // NodeID
	Sig           []byte                 `protobuf:"bytes,9,opt,name=sig,proto3" json:"sig,omitempty"`                                     // Ed25519 by publisher over entire manifest
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Manifest) Reset() {
	*x = Manifest{}
	mi := &file_content_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manifest) ProtoMessage() {}

func (x *Manifest) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manifest.ProtoReflect.Descriptor instead.
func (*Manifest) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{3}
}

func (x *Manifest) GetBlobHash() []byte {
	if x != nil {
		return x.BlobHash
	}
	return nil
}

func (x *Manifest) GetTotalSize() uint64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *Manifest) GetChunkSize() uint32 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

func (x *Manifest) GetChunks() [][]byte {
	if x != nil {
		return x.Chunks
	}
	return nil
}

func (x *Manifest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Manifest) GetMime() string {
	if x != nil {
		return x.Mime
	}
	return ""
}

func (x *Manifest) GetPublishedAt() int64 {
	if x != nil {
		return x.PublishedAt
	}
	return 0
}

func (x *Manifest) GetPublisher() []byte {
	if x != nil {
		return x.Publisher
	}
	return nil
}

func (x *Manifest) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

var File_content_proto protoreflect.FileDescriptor

const file_content_proto_rawDesc = "" +
	"\n" +
	"\rcontent.proto\x12\bswarm.v1\"\xa1\x01\n" +
	"\rContentAdvert\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash\x12\x16\n" +
	"\x06holder\x18\x02 \x01(\fR\x06holder\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x03R\texpiresAt\x12\x12\n" +
	"\x04size\x18\x04 \x01(\rR\x04size\x12\x1f\n" +
	"\vis_manifest\x18\x05 \x01(\bR\n" +
	"isManifest\x12\x10\n" +
	"\x03sig\x18\x06 \x01(\fR\x03sig\"X\n" +
	"\x12ContentLocateQuery\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash\x12\x1c\n" +
	"\trequester\x18\x02 \x01(\fR\trequester\x12\x10\n" +
	"\x03sig\x18\x03 \x01(\fR\x03sig\"H\n" +
	"\x15ContentLocateResponse\x12/\n" +
	"\x06advert\x18\x01 \x01(\v2\x17.swarm.v1.ContentAdvertR\x06advert\"\x80\x02\n" +
	"\bManifest\x12\x1b\n" +
	"\tblob_hash\x18\x01 \x01(\fR\bblobHash\x12\x1d\n" +
	"\n" +
	"total_size\x18\x02 \x01(\x04R\ttotalSize\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x03 \x01(\rR\tchunkSize\x12\x16\n" +
	"\x06chunks\x18\x04 \x03(\fR\x06chunks\x12\x1a\n" +
	"\bfilename\x18\x05 \x01(\tR\bfilename\x12\x12\n" +
	"\x04mime\x18\x06 \x01(\tR\x04mime\x12!\n" +
	"\fpublished_at\x18\a \x01(\x03R\vpublishedAt\x12\x1c\n" +
	"\tpublisher\x18\b \x01(\fR\tpublisher\x12\x10\n" +
	"\x03sig\x18\t \x01(\fR\x03sigB%Z#github.com/bbmumford/swarm/proto/pbb\x06proto3"

var (
	file_content_proto_rawDescOnce sync.Once
	file_content_proto_rawDescData []byte
)

func file_content_proto_rawDescGZIP() []byte {
	file_content_proto_rawDescOnce.Do(func() {
		file_content_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_content_proto_rawDesc), len(file_content_proto_rawDesc)))
	})
	return file_content_proto_rawDescData
}

var file_content_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_content_proto_goTypes = []any{
	(*ContentAdvert)(nil),         // 0: swarm.v1.ContentAdvert
	(*ContentLocateQuery)(nil),    // 1: swarm.v1.ContentLocateQuery
	(*ContentLocateResponse)(nil), // 2: swarm.v1.ContentLocateResponse
	(*Manifest)(nil),              // 3: swarm.v1.Manifest
}
var file_content_proto_depIdxs = []int32{
	0, // 0: swarm.v1.ContentLocateResponse.advert:type_name -> swarm.v1.ContentAdvert
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_content_proto_init() }
func file_content_proto_init() {
	if File_content_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_content_proto_rawDesc), len(file_content_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_content_proto_goTypes,
		DependencyIndexes: file_content_proto_depIdxs,
		MessageInfos:      file_content_proto_msgTypes,
	}.Build()
	File_content_proto = out.File
	file_content_proto_goTypes = nil
	file_content_proto_depIdxs = nil
}
