// Copyright (c) 2026 HSTLES / ORBTR Pty Ltd. All Rights Reserved.
// Queries: licensing@hstles.com
//
// Unified PeerRecord — one signed Ed25519 envelope per peer per fabric.
//
// Carries identity + addresses + RPC handlers + capabilities + grade +
// multi-network info, all atomic. Updates republish the full record.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: peer_record.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Grade is the QoS / capability tier this peer advertises.
type Grade int32

const (
	Grade_GRADE_UNKNOWN         Grade = 0
	Grade_GRADE_BEST_EFFORT     Grade = 1
	Grade_GRADE_RELIABLE        Grade = 2
	Grade_GRADE_LOW_LATENCY     Grade = 3
	Grade_GRADE_HIGH_THROUGHPUT Grade = 4
)

// Enum value maps for Grade.
var (
	Grade_name = map[int32]string{
		0: "GRADE_UNKNOWN",
		1: "GRADE_BEST_EFFORT",
		2: "GRADE_RELIABLE",
		3: "GRADE_LOW_LATENCY",
		4: "GRADE_HIGH_THROUGHPUT",
	}
	Grade_value = map[string]int32{
		"GRADE_UNKNOWN":         0,
		"GRADE_BEST_EFFORT":     1,
		"GRADE_RELIABLE":        2,
		"GRADE_LOW_LATENCY":     3,
		"GRADE_HIGH_THROUGHPUT": 4,
	}
)

func (x Grade) Enum() *Grade {
	p := new(Grade)
	*p = x
	return p
}

func (x Grade) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Grade) Descriptor() protoreflect.EnumDescriptor {
	return file_peer_record_proto_enumTypes[0].Descriptor()
}

func (Grade) Type() protoreflect.EnumType {
	return &file_peer_record_proto_enumTypes[0]
}

func (x Grade) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Grade.Descriptor instead.
func (Grade) EnumDescriptor() ([]byte, []int) {
	return file_peer_record_proto_rawDescGZIP(), []int{0}
}

// QuarantineState describes a peer's isolation status.
type QuarantineState int32

const (
	QuarantineState_QUARANTINE_NONE    QuarantineState = 0 // not quarantined
	QuarantineState_QUARANTINE_ACTIVE  QuarantineState = 1 // currently isolated; routing should exclude
	QuarantineState_QUARANTINE_CLEARED QuarantineState = 2 // recently lifted; allow but log
)

// Enum value maps for QuarantineState.
var (
	QuarantineState_name = map[int32]string{
		0: "QUARANTINE_NONE",
		1: "QUARANTINE_ACTIVE",
		2: "QUARANTINE_CLEARED",
	}
	QuarantineState_value = map[string]int32{
		"QUARANTINE_NONE":    0,
		"QUARANTINE_ACTIVE":  1,
		"QUARANTINE_CLEARED": 2,
	}
)

func (x QuarantineState) Enum() *QuarantineState {
	p := new(QuarantineState)
	*p = x
	return p
}

func (x QuarantineState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QuarantineState) Descriptor() protoreflect.EnumDescriptor {
	return file_peer_record_proto_enumTypes[1].Descriptor()
}

func (QuarantineState) Type() protoreflect.EnumType {
	return &file_peer_record_proto_enumTypes[1]
}

func (x QuarantineState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QuarantineState.Descriptor instead.
func (QuarantineState) EnumDescriptor() ([]byte, []int) {
	return file_peer_record_proto_rawDescGZIP(), []int{1}
}

type Address_Transport int32

const (
	Address_UNKNOWN   Address_Transport = 0
	Address_NOISE_UDP Address_Transport = 1
	Address_WEBSOCKET Address_Transport = 2
	Address_GRPC      Address_Transport = 3
	Address_HTTP      Address_Transport = 4
)

// Enum value maps for Address_Transport.
var (
	Address_Transport_name = map[int32]string{
		0: "UNKNOWN",
		1: "NOISE_UDP",
		2: "WEBSOCKET",
		3: "GRPC",
		4: "HTTP",
	}
	Address_Transport_value = map[string]int32{
		"UNKNOWN":   0,
		"NOISE_UDP": 1,
		"WEBSOCKET": 2,
		"GRPC":      3,
		"HTTP":      4,
	}
)

func (x Address_Transport) Enum() *Address_Transport {
	p := new(Address_Transport)
	*p = x
	return p
}

func (x Address_Transport) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Address_Transport) Descriptor() protoreflect.EnumDescriptor {
	return file_peer_record_proto_enumTypes[2].Descriptor()
}

func (Address_Transport) Type() protoreflect.EnumType {
	return &file_peer_record_proto_enumTypes[2]
}

func (x Address_Transport) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Address_Transport.Descriptor instead.
func (Address_Transport) EnumDescriptor() ([]byte, []int) {
	return file_peer_record_proto_rawDescGZIP(), []int{1, 0}
}

// PeerRecord lives in the body of a swarm.Record on topics like
// "fleet.peer" or "agent.peer.<tenantID>.<networkID>".
type PeerRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ---------- Identity ----------
	NodeId    []byte `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`           // Ed25519 pubkey
	Epoch     uint64 `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`                          // republish counter; monotonic per node_id
	IssuedAt  int64  `protobuf:"varint,3,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`    // unix nanoseconds
	ExpiresAt int64  `protobuf:"varint,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // unix nanoseconds (0 = no expiry)
	// ---------- Addresses ----------
	Addresses []*Address `protobuf:"bytes,5,rep,name=addresses,proto3" json:"addresses,omitempty"`
	// ---------- RPC handlers + grade ----------
	RpcHandlers []string `protobuf:"bytes,6,rep,name=rpc_handlers,json=rpcHandlers,proto3" json:"rpc_handlers,omitempty"`             // fully-qualified names this peer serves
	Grade       Grade    `protobuf:"varint,7,opt,name=grade,proto3,enum=swarm.v1.Grade" json:"grade,omitempty"`                       // QoS class (preferred for dispatch)
	MaxGrade    Grade    `protobuf:"varint,8,opt,name=max_grade,json=maxGrade,proto3,enum=swarm.v1.Grade" json:"max_grade,omitempty"` // capability ceiling
	// ---------- Capabilities ----------
	Capabilities *Capabilities `protobuf:"bytes,9,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	// ---------- Multi-network membership (agent fabric) ----------
	Networks []*NetworkInfo `protobuf:"bytes,10,rep,name=networks,proto3" json:"networks,omitempty"`
	// ---------- Signature ----------
	Sig           []byte `protobuf:"bytes,99,opt,name=sig,proto3" json:"sig,omitempty"` // Ed25519 over wire-format excluding sig
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerRecord) Reset() {
	*x = PeerRecord{}
	mi := &file_peer_record_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerRecord) ProtoMessage() {}

func (x *PeerRecord) ProtoReflect() protoreflect.Message {
	mi := &file_peer_record_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerRecord.ProtoReflect.Descriptor instead.
func (*PeerRecord) Descriptor() ([]byte, []int) {
	return file_peer_record_proto_rawDescGZIP(), []int{0}
}

func (x *PeerRecord) GetNodeId() []byte {
	if x != nil {
		return x.NodeId
	}
	return nil
}

func (x *PeerRecord) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *PeerRecord) GetIssuedAt() int64 {
	if x != nil {
		return x.IssuedAt
	}
	return 0
}

func (x *PeerRecord) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *PeerRecord) GetAddresses() []*Address {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *PeerRecord) GetRpcHandlers() []string {
	if x != nil {
		return x.RpcHandlers
	}
	return nil
}

func (x *PeerRecord) GetGrade() Grade {
	if x != nil {
		return x.Grade
	}
	return Grade_GRADE_UNKNOWN
}

func (x *PeerRecord) GetMaxGrade() Grade {
	if x != nil {
		return x.MaxGrade
	}
	return Grade_GRADE_UNKNOWN
}

func (x *PeerRecord) GetCapabilities() *Capabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *PeerRecord) GetNetworks() []*NetworkInfo {
	if x != nil {
		return x.Networks
	}
	return nil
}

func (x *PeerRecord) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

// Address advertises a way to reach this peer.
type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transport     Address_Transport      `protobuf:"varint,1,opt,name=transport,proto3,enum=swarm.v1.Address_Transport" json:"transport,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"` // IP or hostname
	Port          uint32                 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Sni           string                 `protobuf:"bytes,4,opt,name=sni,proto3" json:"sni,omitempty"`                                             // optional TLS SNI hint
	RttEstimateMs uint32                 `protobuf:"varint,5,opt,name=rtt_estimate_ms,json=rttEstimateMs,proto3" json:"rtt_estimate_ms,omitempty"` // observed RTT for adaptive selection
	RegionHint    uint32                 `protobuf:"varint,6,opt,name=region_hint,json=regionHint,proto3" json:"region_hint,omitempty"`            // fly region or geo code (advisory)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_peer_record_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_peer_record_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_peer_record_proto_rawDescGZIP(), []int{1}
}

func (x *Address) GetTransport() Address_Transport {
	if x != nil {
		return x.Transport
	}
	return Address_UNKNOWN
}

func (x *Address) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Address) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Address) GetSni() string {
	if x != nil {
		return x.Sni
	}
	return ""
}

func (x *Address) GetRttEstimateMs() uint32 {
	if x != nil {
		return x.RttEstimateMs
	}
	return 0
}

func (x *Address) GetRegionHint() uint32 {
	if x != nil {
		return x.RegionHint
	}
	return 0
}

// Capabilities advertises peer attributes for routing + RPC dispatch + policy.
type Capabilities struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Roles            []string               `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`                                                                              // anchor, relay, edge, dhcp, print, ddns, egress
	Tags             []string               `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`                                                                                // arbitrary k=v style tag strings ("env=prod")
	QuarantineStatus QuarantineState        `protobuf:"varint,3,opt,name=quarantine_status,json=quarantineStatus,proto3,enum=swarm.v1.QuarantineState" json:"quarantine_status,omitempty"` // active/cleared/none
	InspectionMode   string                 `protobuf:"bytes,4,opt,name=inspection_mode,json=inspectionMode,proto3" json:"inspection_mode,omitempty"`                                      // "off" | "lite" | "full"
	EffectiveTags    []string               `protobuf:"bytes,5,rep,name=effective_tags,json=effectiveTags,proto3" json:"effective_tags,omitempty"`                                         // tag expression results after policy compilation
	SegmentAffinity  []*SegmentSpec         `protobuf:"bytes,6,rep,name=segment_affinity,json=segmentAffinity,proto3" json:"segment_affinity,omitempty"`                                   // VRF/VLAN assignments for edge-role peers
	ActiveUsers      []*UserSession         `protobuf:"bytes,7,rep,name=active_users,json=activeUsers,proto3" json:"active_users,omitempty"`                                               // who's logged in (multi-session)
	EdgeRoles        []string               `protobuf:"bytes,8,rep,name=edge_roles,json=edgeRoles,proto3" json:"edge_roles,omitempty"`                                                     // telemetry-aggregator, otel-exporter, c2-cache, signaling-relay, snmp-discoverer, tuf-cache
	SchemaVersion    uint32                 `protobuf:"varint,9,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`                                        // for skew detection during rolling upgrades
	PolicyEpoch      uint64                 `protobuf:"varint,10,opt,name=policy_epoch,json=policyEpoch,proto3" json:"policy_epoch,omitempty"`                                             // for anti-rollback consensus
	C2LastSyncAgeMs  uint64                 `protobuf:"varint,11,opt,name=c2_last_sync_age_ms,json=c2LastSyncAgeMs,proto3" json:"c2_last_sync_age_ms,omitempty"`                           // freshness signal for c2-cache role
	DhcpServerAddr   string                 `protobuf:"bytes,12,opt,name=dhcp_server_addr,json=dhcpServerAddr,proto3" json:"dhcp_server_addr,omitempty"`                                   // when edge serves DHCP, advertise address
	// Free-form k=v capability bag for forward extension. Subject to the
	// 16 KB Record max — keep lean.
	Extras        map[string]string `protobuf:"bytes,99,rep,name=extras,proto3" json:"extras,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Capabilities) Reset() {
	*x = Capabilities{}
	mi := &file_peer_record_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capabilities) ProtoMessage() {}

func (x *Capabilities) ProtoReflect() protoreflect.Message {
	mi := &file_peer_record_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capabilities.ProtoReflect.Descriptor instead.
func (*Capabilities) Descriptor() ([]byte, []int) {
	return file_peer_record_proto_rawDescGZIP(), []int{2}
}

func (x *Capabilities) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *Capabilities) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Capabilities) GetQuarantineStatus() QuarantineState {
	if x != nil {
		return x.QuarantineStatus
	}
	return QuarantineState_QUARANTINE_NONE
}

func (x *Capabilities) GetInspectionMode() string {
	if x != nil {
		return x.InspectionMode
	}
	return ""
}

func (x *Capabilities) GetEffectiveTags() []string {
	if x != nil {
		return x.EffectiveTags
	}
	return nil
}

func (x *Capabilities) GetSegmentAffinity() []*SegmentSpec {
	if x != nil {
		return x.SegmentAffinity
	}
	return nil
}

func (x *Capabilities) GetActiveUsers() []*UserSession {
	if x != nil {
		return x.ActiveUsers
	}
	return nil
}

func (x *Capabilities) GetEdgeRoles() []string {
	if x != nil {
		return x.EdgeRoles
	}
	return nil
}

func (x *Capabilities) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *Capabilities) GetPolicyEpoch() uint64 {
	if x != nil {
		return x.PolicyEpoch
	}
	return 0
}

func (x *Capabilities) GetC2LastSyncAgeMs() uint64 {
	if x != nil {
		return x.C2LastSyncAgeMs
	}
	return 0
}

func (x *Capabilities) GetDhcpServerAddr() string {
	if x != nil {
		return x.DhcpServerAddr
	}
	return ""
}

func (x *Capabilities) GetExtras() map[string]string {
	if x != nil {
		return x.Extras
	}
	return nil
}

// SegmentSpec advertises VRF/VLAN ownership for edge-role peers.
type SegmentSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VrfName       string                 `protobuf:"bytes,1,opt,name=vrf_name,json=vrfName,proto3" json:"vrf_name,omitempty"`
	VlanId        uint32                 `protobuf:"varint,2,opt,name=vlan_id,json=vlanId,proto3" json:"vlan_id,omitempty"`
	NatPoolCidr   string                 `protobuf:"bytes,3,opt,name=nat_pool_cidr,json=natPoolCidr,proto3" json:"nat_pool_cidr,omitempty"` // optional
	Primary       bool                   `protobuf:"varint,4,opt,name=primary,proto3" json:"primary,omitempty"`                             // primary owner vs secondary
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SegmentSpec) Reset() {
	*x = SegmentSpec{}
	mi := &file_peer_record_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SegmentSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentSpec) ProtoMessage() {}

func (x *SegmentSpec) ProtoReflect() protoreflect.Message {
	mi := &file_peer_record_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentSpec.ProtoReflect.Descriptor instead.
func (*SegmentSpec) Descriptor() ([]byte, []int) {
	return file_peer_record_proto_rawDescGZIP(), []int{3}
}

func (x *SegmentSpec) GetVrfName() string {
	if x != nil {
		return x.VrfName
	}
	return ""
}

func (x *SegmentSpec) GetVlanId() uint32 {
	if x != nil {
		return x.VlanId
	}
	return 0
}

func (x *SegmentSpec) GetNatPoolCidr() string {
	if x != nil {
		return x.NatPoolCidr
	}
	return ""
}

func (x *SegmentSpec) GetPrimary() bool {
	if x != nil {
		return x.Primary
	}
	return false
}

// UserSession advertises an active OS-user session on this peer (for multi-
// session VDI awareness). Includes only non-PII identifiers.
type UserSession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // OS session ID
	UserHash      string                 `protobuf:"bytes,2,opt,name=user_hash,json=userHash,proto3" json:"user_hash,omitempty"`    // SHA256(user@domain) for cross-peer correlation without PII
	Since         int64                  `protobuf:"varint,3,opt,name=since,proto3" json:"since,omitempty"`                         // unix nanoseconds
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`                          // "active" | "cached" | "none"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSession) Reset() {
	*x = UserSession{}
	mi := &file_peer_record_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSession) ProtoMessage() {}

func (x *UserSession) ProtoReflect() protoreflect.Message {
	mi := &file_peer_record_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSession.ProtoReflect.Descriptor instead.
func (*UserSession) Descriptor() ([]byte, []int) {
	return file_peer_record_proto_rawDescGZIP(), []int{4}
}

func (x *UserSession) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *UserSession) GetUserHash() string {
	if x != nil {
		return x.UserHash
	}
	return ""
}

func (x *UserSession) GetSince() int64 {
	if x != nil {
		return x.Since
	}
	return 0
}

func (x *UserSession) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

// NetworkInfo describes an agent's overlay membership in one network.
type NetworkInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NetworkId     string                 `protobuf:"bytes,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	OverlayIp     string                 `protobuf:"bytes,2,opt,name=overlay_ip,json=overlayIp,proto3" json:"overlay_ip,omitempty"` // e.g. "10.147.20.15"
	Mtu           uint32                 `protobuf:"varint,3,opt,name=mtu,proto3" json:"mtu,omitempty"`
	Primary       bool                   `protobuf:"varint,4,opt,name=primary,proto3" json:"primary,omitempty"` // is this the default network?
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkInfo) Reset() {
	*x = NetworkInfo{}
	mi := &file_peer_record_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkInfo) ProtoMessage() {}

func (x *NetworkInfo) ProtoReflect() protoreflect.Message {
	mi := &file_peer_record_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkInfo.ProtoReflect.Descriptor instead.
func (*NetworkInfo) Descriptor() ([]byte, []int) {
	return file_peer_record_proto_rawDescGZIP(), []int{5}
}

func (x *NetworkInfo) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

func (x *NetworkInfo) GetOverlayIp() string {
	if x != nil {
		return x.OverlayIp
	}
	return ""
}

func (x *NetworkInfo) GetMtu() uint32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

func (x *NetworkInfo) GetPrimary() bool {
	if x != nil {
		return x.Primary
	}
	return false
}

var File_peer_record_proto protoreflect.FileDescriptor

const file_peer_record_proto_rawDesc = "" +
	"\n" +
	"\x11peer_record.proto\x12\bswarm.v1\"\xa1\x03\n" +
	"\n" +
	"PeerRecord\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\fR\x06nodeId\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x04R\x05epoch\x12\x1b\n" +
	"\tissued_at\x18\x03 \x01(\x03R\bissuedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\x03R\texpiresAt\x12/\n" +
	"\taddresses\x18\x05 \x03(\v2\x11.swarm.v1.AddressR\taddresses\x12!\n" +
	"\frpc_handlers\x18\x06 \x03(\tR\vrpcHandlers\x12%\n" +
	"\x05grade\x18\a \x01(\x0e2\x0f.swarm.v1.GradeR\x05grade\x12,\n" +
	"\tmax_grade\x18\b \x01(\x0e2\x0f.swarm.v1.GradeR\bmaxGrade\x12:\n" +
	"\fcapabilities\x18\t \x01(\v2\x16.swarm.v1.CapabilitiesR\fcapabilities\x121\n" +
	"\bnetworks\x18\n" +
	" \x03(\v2\x15.swarm.v1.NetworkInfoR\bnetworks\x12\x10\n" +
	"\x03sig\x18c \x01(\fR\x03sig\"\x93\x02\n" +
	"\aAddress\x129\n" +
	"\ttransport\x18\x01 \x01(\x0e2\x1b.swarm.v1.Address.TransportR\ttransport\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x03 \x01(\rR\x04port\x12\x10\n" +
	"\x03sni\x18\x04 \x01(\tR\x03sni\x12&\n" +
	"\x0frtt_estimate_ms\x18\x05 \x01(\rR\rrttEstimateMs\x12\x1f\n" +
	"\vregion_hint\x18\x06 \x01(\rR\n" +
	"regionHint\"J\n" +
	"\tTransport\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\r\n" +
	"\tNOISE_UDP\x10\x01\x12\r\n" +
	"\tWEBSOCKET\x10\x02\x12\b\n" +
	"\x04GRPC\x10\x03\x12\b\n" +
	"\x04HTTP\x10\x04\"\x84\x05\n" +
	"\fCapabilities\x12\x14\n" +
	"\x05roles\x18\x01 \x03(\tR\x05roles\x12\x12\n" +
	"\x04tags\x18\x02 \x03(\tR\x04tags\x12F\n" +
	"\x11quarantine_status\x18\x03 \x01(\x0e2\x19.swarm.v1.QuarantineStateR\x10quarantineStatus\x12'\n" +
	"\x0finspection_mode\x18\x04 \x01(\tR\x0einspectionMode\x12%\n" +
	"\x0eeffective_tags\x18\x05 \x03(\tR\reffectiveTags\x12@\n" +
	"\x10segment_affinity\x18\x06 \x03(\v2\x15.swarm.v1.SegmentSpecR\x0fsegmentAffinity\x128\n" +
	"\factive_users\x18\a \x03(\v2\x15.swarm.v1.UserSessionR\vactiveUsers\x12\x1d\n" +
	"\n" +
	"edge_roles\x18\b \x03(\tR\tedgeRoles\x12%\n" +
	"\x0eschema_version\x18\t \x01(\rR\rschemaVersion\x12!\n" +
	"\fpolicy_epoch\x18\n" +
	" \x01(\x04R\vpolicyEpoch\x12,\n" +
	"\x13c2_last_sync_age_ms\x18\v \x01(\x04R\x0fc2LastSyncAgeMs\x12(\n" +
	"\x10dhcp_server_addr\x18\f \x01(\tR\x0edhcpServerAddr\x12:\n" +
	"\x06extras\x18c \x03(\v2\".swarm.v1.Capabilities.ExtrasEntryR\x06extras\x1a9\n" +
	"\vExtrasEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x7f\n" +
	"\vSegmentSpec\x12\x19\n" +
	"\bvrf_name\x18\x01 \x01(\tR\avrfName\x12\x17\n" +
	"\avlan_id\x18\x02 \x01(\rR\x06vlanId\x12\"\n" +
	"\rnat_pool_cidr\x18\x03 \x01(\tR\vnatPoolCidr\x12\x18\n" +
	"\aprimary\x18\x04 \x01(\bR\aprimary\"u\n" +
	"\vUserSession\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tuser_hash\x18\x02 \x01(\tR\buserHash\x12\x14\n" +
	"\x05since\x18\x03 \x01(\x03R\x05since\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\"w\n" +
	"\vNetworkInfo\x12\x1d\n" +
	"\n" +
	"network_id\x18\x01 \x01(\tR\tnetworkId\x12\x1d\n" +
	"\n" +
	"overlay_ip\x18\x02 \x01(\tR\toverlayIp\x12\x10\n" +
	"\x03mtu\x18\x03 \x01(\rR\x03mtu\x12\x18\n" +
	"\aprimary\x18\x04 \x01(\bR\aprimary*w\n" +
	"\x05Grade\x12\x11\n" +
	"\rGRADE_UNKNOWN\x10\x00\x12\x15\n" +
	"\x11GRADE_BEST_EFFORT\x10\x01\x12\x12\n" +
	"\x0eGRADE_RELIABLE\x10\x02\x12\x15\n" +
	"\x11GRADE_LOW_LATENCY\x10\x03\x12\x19\n" +
	"\x15GRADE_HIGH_THROUGHPUT\x10\x04*U\n" +
	"\x0fQuarantineState\x12\x13\n" +
	"\x0fQUARANTINE_NONE\x10\x00\x12\x15\n" +
	"\x11QUARANTINE_ACTIVE\x10\x01\x12\x16\n" +
	"\x12QUARANTINE_CLEARED\x10\x02B%Z#github.com/bbmumford/swarm/proto/pbb\x06proto3"

var (
	file_peer_record_proto_rawDescOnce sync.Once
	file_peer_record_proto_rawDescData []byte
)

func file_peer_record_proto_rawDescGZIP() []byte {
	file_peer_record_proto_rawDescOnce.Do(func() {
		file_peer_record_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_peer_record_proto_rawDesc), len(file_peer_record_proto_rawDesc)))
	})
	return file_peer_record_proto_rawDescData
}

var file_peer_record_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_peer_record_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_peer_record_proto_goTypes = []any{
	(Grade)(0),             // 0: swarm.v1.Grade
	(QuarantineState)(0),   // 1: swarm.v1.QuarantineState
	(Address_Transport)(0), // 2: swarm.v1.Address.Transport
	(*PeerRecord)(nil),     // 3: swarm.v1.PeerRecord
	(*Address)(nil),        // 4: swarm.v1.Address
	(*Capabilities)(nil),   // 5: swarm.v1.Capabilities
	(*SegmentSpec)(nil),    // 6: swarm.v1.SegmentSpec
	(*UserSession)(nil),    // 7: swarm.v1.UserSession
	(*NetworkInfo)(nil),    // 8: swarm.v1.NetworkInfo
	nil,                    // 9: swarm.v1.Capabilities.ExtrasEntry
}
var file_peer_record_proto_depIdxs = []int32{
	4,  // 0: swarm.v1.PeerRecord.addresses:type_name -> swarm.v1.Address
	0,  // 1: swarm.v1.PeerRecord.grade:type_name -> swarm.v1.Grade
	0,  // 2: swarm.v1.PeerRecord.max_grade:type_name -> swarm.v1.Grade
	5,  // 3: swarm.v1.PeerRecord.capabilities:type_name -> swarm.v1.Capabilities
	8,  // 4: swarm.v1.PeerRecord.networks:type_name -> swarm.v1.NetworkInfo
	2,  // 5: swarm.v1.Address.transport:type_name -> swarm.v1.Address.Transport
	1,  // 6: swarm.v1.Capabilities.quarantine_status:type_name -> swarm.v1.QuarantineState
	6,  // 7: swarm.v1.Capabilities.segment_affinity:type_name -> swarm.v1.SegmentSpec
	7,  // 8: swarm.v1.Capabilities.active_users:type_name -> swarm.v1.UserSession
	9,  // 9: swarm.v1.Capabilities.extras:type_name -> swarm.v1.Capabilities.ExtrasEntry
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_peer_record_proto_init() }
func file_peer_record_proto_init() {
	if File_peer_record_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_peer_record_proto_rawDesc), len(file_peer_record_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_peer_record_proto_goTypes,
		DependencyIndexes: file_peer_record_proto_depIdxs,
		EnumInfos:         file_peer_record_proto_enumTypes,
		MessageInfos:      file_peer_record_proto_msgTypes,
	}.Build()
	File_peer_record_proto = out.File
	file_peer_record_proto_goTypes = nil
	file_peer_record_proto_depIdxs = nil
}
