// Copyright (c) 2026 HSTLES / ORBTR Pty Ltd. All Rights Reserved.
// Queries: licensing@hstles.com
//
// Swarm protocol wire format — Plumtrees frames + δ-CRDT record envelope.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: swarm.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Record is the signed envelope carried over the swarm. Body is opaque
// at the transport layer — consumers register typed subscribers per Topic.
//
// HLC (hybrid logical clock) gives total order. Sig covers:
//
//	topic || node_id || hlc || body || tombstone || pub_key
//
// node_id is an opaque identifier (caller-defined; may be a fingerprint or
// other non-reversible encoding of pub_key). pub_key is the raw 32-byte
// Ed25519 public key used to verify sig — the receiver MUST verify against
// pub_key directly (not against any key derived from node_id). When the
// caller cares about the node_id ↔ pub_key relationship (e.g. fingerprint
// scheme), the application layer enforces it on top of sig verification.
type Record struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`                 // tenant- and network-scoped topic name
	NodeId        []byte                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // opaque origin identifier (application-defined)
	Hlc           uint64                 `protobuf:"varint,3,opt,name=hlc,proto3" json:"hlc,omitempty"`                    // hybrid logical clock
	Body          []byte                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`                   // opaque; topic-typed
	Tombstone     bool                   `protobuf:"varint,5,opt,name=tombstone,proto3" json:"tombstone,omitempty"`        // body should be empty when true
	Sig           []byte                 `protobuf:"bytes,6,opt,name=sig,proto3" json:"sig,omitempty"`                     // Ed25519 over (topic || node_id || hlc || body || tombstone || pub_key)
	PubKey        []byte                 `protobuf:"bytes,7,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"` // raw 32-byte Ed25519 public key used to verify sig
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_swarm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{0}
}

func (x *Record) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Record) GetNodeId() []byte {
	if x != nil {
		return x.NodeId
	}
	return nil
}

func (x *Record) GetHlc() uint64 {
	if x != nil {
		return x.Hlc
	}
	return 0
}

func (x *Record) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Record) GetTombstone() bool {
	if x != nil {
		return x.Tombstone
	}
	return false
}

func (x *Record) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

func (x *Record) GetPubKey() []byte {
	if x != nil {
		return x.PubKey
	}
	return nil
}

// Frame is the on-wire envelope for swarm protocol messages.
type Frame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Frame_Eager
	//	*Frame_Ihave
	//	*Frame_Graft
	//	*Frame_Prune
	//	*Frame_Merkle
	//	*Frame_MerkleRange
	//	*Frame_Keepalive
	//	*Frame_FetchReq
	//	*Frame_FetchResp
	Kind          isFrame_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_swarm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{1}
}

func (x *Frame) GetKind() isFrame_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Frame) GetEager() *EagerPush {
	if x != nil {
		if x, ok := x.Kind.(*Frame_Eager); ok {
			return x.Eager
		}
	}
	return nil
}

func (x *Frame) GetIhave() *IHave {
	if x != nil {
		if x, ok := x.Kind.(*Frame_Ihave); ok {
			return x.Ihave
		}
	}
	return nil
}

func (x *Frame) GetGraft() *Graft {
	if x != nil {
		if x, ok := x.Kind.(*Frame_Graft); ok {
			return x.Graft
		}
	}
	return nil
}

func (x *Frame) GetPrune() *Prune {
	if x != nil {
		if x, ok := x.Kind.(*Frame_Prune); ok {
			return x.Prune
		}
	}
	return nil
}

func (x *Frame) GetMerkle() *MerkleProbe {
	if x != nil {
		if x, ok := x.Kind.(*Frame_Merkle); ok {
			return x.Merkle
		}
	}
	return nil
}

func (x *Frame) GetMerkleRange() *MerkleRange {
	if x != nil {
		if x, ok := x.Kind.(*Frame_MerkleRange); ok {
			return x.MerkleRange
		}
	}
	return nil
}

func (x *Frame) GetKeepalive() *Keepalive {
	if x != nil {
		if x, ok := x.Kind.(*Frame_Keepalive); ok {
			return x.Keepalive
		}
	}
	return nil
}

func (x *Frame) GetFetchReq() *ContentFetchRequest {
	if x != nil {
		if x, ok := x.Kind.(*Frame_FetchReq); ok {
			return x.FetchReq
		}
	}
	return nil
}

func (x *Frame) GetFetchResp() *ContentFetchResponse {
	if x != nil {
		if x, ok := x.Kind.(*Frame_FetchResp); ok {
			return x.FetchResp
		}
	}
	return nil
}

type isFrame_Kind interface {
	isFrame_Kind()
}

type Frame_Eager struct {
	Eager *EagerPush `protobuf:"bytes,1,opt,name=eager,proto3,oneof"` // tree-edge eager push (full Record)
}

type Frame_Ihave struct {
	Ihave *IHave `protobuf:"bytes,2,opt,name=ihave,proto3,oneof"` // lazy push announcement (digest only)
}

type Frame_Graft struct {
	Graft *Graft `protobuf:"bytes,3,opt,name=graft,proto3,oneof"` // tree-edge promotion
}

type Frame_Prune struct {
	Prune *Prune `protobuf:"bytes,4,opt,name=prune,proto3,oneof"` // tree-edge demotion
}

type Frame_Merkle struct {
	Merkle *MerkleProbe `protobuf:"bytes,5,opt,name=merkle,proto3,oneof"` // anti-entropy probe
}

type Frame_MerkleRange struct {
	MerkleRange *MerkleRange `protobuf:"bytes,6,opt,name=merkle_range,json=merkleRange,proto3,oneof"` // anti-entropy range reconciliation
}

type Frame_Keepalive struct {
	Keepalive *Keepalive `protobuf:"bytes,7,opt,name=keepalive,proto3,oneof"` // empty payload, keeps tree edge alive
}

type Frame_FetchReq struct {
	FetchReq *ContentFetchRequest `protobuf:"bytes,8,opt,name=fetch_req,json=fetchReq,proto3,oneof"` // point-to-point content pull
}

type Frame_FetchResp struct {
	FetchResp *ContentFetchResponse `protobuf:"bytes,9,opt,name=fetch_resp,json=fetchResp,proto3,oneof"` // point-to-point content reply
}

func (*Frame_Eager) isFrame_Kind() {}

func (*Frame_Ihave) isFrame_Kind() {}

func (*Frame_Graft) isFrame_Kind() {}

func (*Frame_Prune) isFrame_Kind() {}

func (*Frame_Merkle) isFrame_Kind() {}

func (*Frame_MerkleRange) isFrame_Kind() {}

func (*Frame_Keepalive) isFrame_Kind() {}

func (*Frame_FetchReq) isFrame_Kind() {}

func (*Frame_FetchResp) isFrame_Kind() {}

// ContentFetchRequest is a point-to-point pull of content addressed by
// SHA256 hash. The receiver looks up its local ContentProvider and
// returns the bytes (or an error) in a paired ContentFetchResponse.
// The request_id is opaque correlation owned by the originator; the
// receiver echoes it on the response so the originator can route the
// reply back to the waiting Fetch call.
type ContentFetchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Hash          []byte                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"` // SHA256 of requested content (32 bytes)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentFetchRequest) Reset() {
	*x = ContentFetchRequest{}
	mi := &file_swarm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentFetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentFetchRequest) ProtoMessage() {}

func (x *ContentFetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentFetchRequest.ProtoReflect.Descriptor instead.
func (*ContentFetchRequest) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{2}
}

func (x *ContentFetchRequest) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *ContentFetchRequest) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

// ContentFetchResponse carries the requested bytes (or an error) back
// to the originator. error is non-empty when the receiver cannot serve
// the request (not held, provider unavailable, etc.) and body is empty
// in that case.
type ContentFetchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Body          []byte                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`   // empty when error is set
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"` // empty on success
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentFetchResponse) Reset() {
	*x = ContentFetchResponse{}
	mi := &file_swarm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentFetchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentFetchResponse) ProtoMessage() {}

func (x *ContentFetchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentFetchResponse.ProtoReflect.Descriptor instead.
func (*ContentFetchResponse) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{3}
}

func (x *ContentFetchResponse) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *ContentFetchResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ContentFetchResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// EagerPush carries the full Record along tree edges.
type EagerPush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *Record                `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	Ttl           uint32                 `protobuf:"varint,2,opt,name=ttl,proto3" json:"ttl,omitempty"` // bounded fan-out
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EagerPush) Reset() {
	*x = EagerPush{}
	mi := &file_swarm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EagerPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EagerPush) ProtoMessage() {}

func (x *EagerPush) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EagerPush.ProtoReflect.Descriptor instead.
func (*EagerPush) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{4}
}

func (x *EagerPush) GetRecord() *Record {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *EagerPush) GetTtl() uint32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

// IHave announces a digest of a Record to non-tree-edge peers. They can
// then issue a Graft to pull the full Record.
type IHave struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	NodeId        []byte                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Hlc           uint64                 `protobuf:"varint,3,opt,name=hlc,proto3" json:"hlc,omitempty"`
	BodyHash      []byte                 `protobuf:"bytes,4,opt,name=body_hash,json=bodyHash,proto3" json:"body_hash,omitempty"` // SHA256(body)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IHave) Reset() {
	*x = IHave{}
	mi := &file_swarm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IHave) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IHave) ProtoMessage() {}

func (x *IHave) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IHave.ProtoReflect.Descriptor instead.
func (*IHave) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{5}
}

func (x *IHave) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *IHave) GetNodeId() []byte {
	if x != nil {
		return x.NodeId
	}
	return nil
}

func (x *IHave) GetHlc() uint64 {
	if x != nil {
		return x.Hlc
	}
	return 0
}

func (x *IHave) GetBodyHash() []byte {
	if x != nil {
		return x.BodyHash
	}
	return nil
}

// Graft promotes the sender to a tree edge from the receiver's perspective.
type Graft struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	NodeId        []byte                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // the Record's origin we want to pull
	Hlc           uint64                 `protobuf:"varint,3,opt,name=hlc,proto3" json:"hlc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Graft) Reset() {
	*x = Graft{}
	mi := &file_swarm_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Graft) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Graft) ProtoMessage() {}

func (x *Graft) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Graft.ProtoReflect.Descriptor instead.
func (*Graft) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{6}
}

func (x *Graft) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Graft) GetNodeId() []byte {
	if x != nil {
		return x.NodeId
	}
	return nil
}

func (x *Graft) GetHlc() uint64 {
	if x != nil {
		return x.Hlc
	}
	return 0
}

// Prune demotes the sender from a tree edge.
type Prune struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"` // optional — empty means all topics
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Prune) Reset() {
	*x = Prune{}
	mi := &file_swarm_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Prune) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Prune) ProtoMessage() {}

func (x *Prune) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Prune.ProtoReflect.Descriptor instead.
func (*Prune) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{7}
}

func (x *Prune) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

// MerkleProbe sends the local Merkle root for a topic + range.
type MerkleProbe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	RangeStart    []byte                 `protobuf:"bytes,2,opt,name=range_start,json=rangeStart,proto3" json:"range_start,omitempty"` // first node_id in range
	RangeEnd      []byte                 `protobuf:"bytes,3,opt,name=range_end,json=rangeEnd,proto3" json:"range_end,omitempty"`       // last node_id in range
	RootHash      []byte                 `protobuf:"bytes,4,opt,name=root_hash,json=rootHash,proto3" json:"root_hash,omitempty"`       // local Merkle root for this range
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerkleProbe) Reset() {
	*x = MerkleProbe{}
	mi := &file_swarm_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerkleProbe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerkleProbe) ProtoMessage() {}

func (x *MerkleProbe) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerkleProbe.ProtoReflect.Descriptor instead.
func (*MerkleProbe) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{8}
}

func (x *MerkleProbe) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *MerkleProbe) GetRangeStart() []byte {
	if x != nil {
		return x.RangeStart
	}
	return nil
}

func (x *MerkleProbe) GetRangeEnd() []byte {
	if x != nil {
		return x.RangeEnd
	}
	return nil
}

func (x *MerkleProbe) GetRootHash() []byte {
	if x != nil {
		return x.RootHash
	}
	return nil
}

// MerkleRange is the response: send all Records in a range (or a sub-range
// hash chain if too large).
type MerkleRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Records       []*Record              `protobuf:"bytes,2,rep,name=records,proto3" json:"records,omitempty"`
	Truncated     bool                   `protobuf:"varint,3,opt,name=truncated,proto3" json:"truncated,omitempty"` // when truncated, caller should split the range
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerkleRange) Reset() {
	*x = MerkleRange{}
	mi := &file_swarm_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerkleRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerkleRange) ProtoMessage() {}

func (x *MerkleRange) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerkleRange.ProtoReflect.Descriptor instead.
func (*MerkleRange) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{9}
}

func (x *MerkleRange) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *MerkleRange) GetRecords() []*Record {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *MerkleRange) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

// Keepalive carries nothing — just maintains tree-edge liveness.
type Keepalive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Keepalive) Reset() {
	*x = Keepalive{}
	mi := &file_swarm_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Keepalive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Keepalive) ProtoMessage() {}

func (x *Keepalive) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Keepalive.ProtoReflect.Descriptor instead.
func (*Keepalive) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{10}
}

var File_swarm_proto protoreflect.FileDescriptor

const file_swarm_proto_rawDesc = "" +
	"\n" +
	"\vswarm.proto\x12\bswarm.v1\"\xa6\x01\n" +
	"\x06Record\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\fR\x06nodeId\x12\x10\n" +
	"\x03hlc\x18\x03 \x01(\x04R\x03hlc\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\x12\x1c\n" +
	"\ttombstone\x18\x05 \x01(\bR\ttombstone\x12\x10\n" +
	"\x03sig\x18\x06 \x01(\fR\x03sig\x12\x17\n" +
	"\apub_key\x18\a \x01(\fR\x06pubKey\"\xd8\x03\n" +
	"\x05Frame\x12+\n" +
	"\x05eager\x18\x01 \x01(\v2\x13.swarm.v1.EagerPushH\x00R\x05eager\x12'\n" +
	"\x05ihave\x18\x02 \x01(\v2\x0f.swarm.v1.IHaveH\x00R\x05ihave\x12'\n" +
	"\x05graft\x18\x03 \x01(\v2\x0f.swarm.v1.GraftH\x00R\x05graft\x12'\n" +
	"\x05prune\x18\x04 \x01(\v2\x0f.swarm.v1.PruneH\x00R\x05prune\x12/\n" +
	"\x06merkle\x18\x05 \x01(\v2\x15.swarm.v1.MerkleProbeH\x00R\x06merkle\x12:\n" +
	"\fmerkle_range\x18\x06 \x01(\v2\x15.swarm.v1.MerkleRangeH\x00R\vmerkleRange\x123\n" +
	"\tkeepalive\x18\a \x01(\v2\x13.swarm.v1.KeepaliveH\x00R\tkeepalive\x12<\n" +
	"\tfetch_req\x18\b \x01(\v2\x1d.swarm.v1.ContentFetchRequestH\x00R\bfetchReq\x12?\n" +
	"\n" +
	"fetch_resp\x18\t \x01(\v2\x1e.swarm.v1.ContentFetchResponseH\x00R\tfetchRespB\x06\n" +
	"\x04kind\"H\n" +
	"\x13ContentFetchRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\fR\x04hash\"_\n" +
	"\x14ContentFetchResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12\x12\n" +
	"\x04body\x18\x02 \x01(\fR\x04body\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"G\n" +
	"\tEagerPush\x12(\n" +
	"\x06record\x18\x01 \x01(\v2\x10.swarm.v1.RecordR\x06record\x12\x10\n" +
	"\x03ttl\x18\x02 \x01(\rR\x03ttl\"e\n" +
	"\x05IHave\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\fR\x06nodeId\x12\x10\n" +
	"\x03hlc\x18\x03 \x01(\x04R\x03hlc\x12\x1b\n" +
	"\tbody_hash\x18\x04 \x01(\fR\bbodyHash\"H\n" +
	"\x05Graft\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\fR\x06nodeId\x12\x10\n" +
	"\x03hlc\x18\x03 \x01(\x04R\x03hlc\"\x1d\n" +
	"\x05Prune\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\"~\n" +
	"\vMerkleProbe\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x1f\n" +
	"\vrange_start\x18\x02 \x01(\fR\n" +
	"rangeStart\x12\x1b\n" +
	"\trange_end\x18\x03 \x01(\fR\brangeEnd\x12\x1b\n" +
	"\troot_hash\x18\x04 \x01(\fR\brootHash\"m\n" +
	"\vMerkleRange\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12*\n" +
	"\arecords\x18\x02 \x03(\v2\x10.swarm.v1.RecordR\arecords\x12\x1c\n" +
	"\ttruncated\x18\x03 \x01(\bR\ttruncated\"\v\n" +
	"\tKeepaliveB%Z#github.com/bbmumford/swarm/proto/pbb\x06proto3"

var (
	file_swarm_proto_rawDescOnce sync.Once
	file_swarm_proto_rawDescData []byte
)

func file_swarm_proto_rawDescGZIP() []byte {
	file_swarm_proto_rawDescOnce.Do(func() {
		file_swarm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_swarm_proto_rawDesc), len(file_swarm_proto_rawDesc)))
	})
	return file_swarm_proto_rawDescData
}

var file_swarm_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_swarm_proto_goTypes = []any{
	(*Record)(nil),               // 0: swarm.v1.Record
	(*Frame)(nil),                // 1: swarm.v1.Frame
	(*ContentFetchRequest)(nil),  // 2: swarm.v1.ContentFetchRequest
	(*ContentFetchResponse)(nil), // 3: swarm.v1.ContentFetchResponse
	(*EagerPush)(nil),            // 4: swarm.v1.EagerPush
	(*IHave)(nil),                // 5: swarm.v1.IHave
	(*Graft)(nil),                // 6: swarm.v1.Graft
	(*Prune)(nil),                // 7: swarm.v1.Prune
	(*MerkleProbe)(nil),          // 8: swarm.v1.MerkleProbe
	(*MerkleRange)(nil),          // 9: swarm.v1.MerkleRange
	(*Keepalive)(nil),            // 10: swarm.v1.Keepalive
}
var file_swarm_proto_depIdxs = []int32{
	4,  // 0: swarm.v1.Frame.eager:type_name -> swarm.v1.EagerPush
	5,  // 1: swarm.v1.Frame.ihave:type_name -> swarm.v1.IHave
	6,  // 2: swarm.v1.Frame.graft:type_name -> swarm.v1.Graft
	7,  // 3: swarm.v1.Frame.prune:type_name -> swarm.v1.Prune
	8,  // 4: swarm.v1.Frame.merkle:type_name -> swarm.v1.MerkleProbe
	9,  // 5: swarm.v1.Frame.merkle_range:type_name -> swarm.v1.MerkleRange
	10, // 6: swarm.v1.Frame.keepalive:type_name -> swarm.v1.Keepalive
	2,  // 7: swarm.v1.Frame.fetch_req:type_name -> swarm.v1.ContentFetchRequest
	3,  // 8: swarm.v1.Frame.fetch_resp:type_name -> swarm.v1.ContentFetchResponse
	0,  // 9: swarm.v1.EagerPush.record:type_name -> swarm.v1.Record
	0,  // 10: swarm.v1.MerkleRange.records:type_name -> swarm.v1.Record
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_swarm_proto_init() }
func file_swarm_proto_init() {
	if File_swarm_proto != nil {
		return
	}
	file_swarm_proto_msgTypes[1].OneofWrappers = []any{
		(*Frame_Eager)(nil),
		(*Frame_Ihave)(nil),
		(*Frame_Graft)(nil),
		(*Frame_Prune)(nil),
		(*Frame_Merkle)(nil),
		(*Frame_MerkleRange)(nil),
		(*Frame_Keepalive)(nil),
		(*Frame_FetchReq)(nil),
		(*Frame_FetchResp)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_swarm_proto_rawDesc), len(file_swarm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_swarm_proto_goTypes,
		DependencyIndexes: file_swarm_proto_depIdxs,
		MessageInfos:      file_swarm_proto_msgTypes,
	}.Build()
	File_swarm_proto = out.File
	file_swarm_proto_goTypes = nil
	file_swarm_proto_depIdxs = nil
}
